# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RuleTranslator.ui'
#
# Created: Sun Feb 16 21:50:40 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(931, 487)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 40, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.serie_properties = QtGui.QGroupBox(self.centralwidget)
        self.serie_properties.setGeometry(QtCore.QRect(70, 80, 291, 151))
        self.serie_properties.setObjectName(_fromUtf8("serie_properties"))
        self.label_5 = QtGui.QLabel(self.serie_properties)
        self.label_5.setGeometry(QtCore.QRect(181, 83, 61, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.min_interval_label = QtGui.QLabel(self.serie_properties)
        self.min_interval_label.setGeometry(QtCore.QRect(31, 53, 71, 16))
        self.min_interval_label.setObjectName(_fromUtf8("min_interval_label"))
        self.max_interval_label = QtGui.QLabel(self.serie_properties)
        self.max_interval_label.setGeometry(QtCore.QRect(31, 83, 71, 16))
        self.max_interval_label.setObjectName(_fromUtf8("max_interval_label"))
        self.max_interval = QtGui.QSpinBox(self.serie_properties)
        self.max_interval.setGeometry(QtCore.QRect(130, 80, 42, 22))
        self.max_interval.setMinimum(1)
        self.max_interval.setMaximum(5)
        self.max_interval.setProperty("value", 5)
        self.max_interval.setObjectName(_fromUtf8("max_interval"))
        self.label_2 = QtGui.QLabel(self.serie_properties)
        self.label_2.setGeometry(QtCore.QRect(181, 53, 61, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.min_interval = QtGui.QSpinBox(self.serie_properties)
        self.min_interval.setGeometry(QtCore.QRect(130, 50, 42, 22))
        self.min_interval.setMinimum(1)
        self.min_interval.setMaximum(5)
        self.min_interval.setObjectName(_fromUtf8("min_interval"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 270, 861, 91))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(790, 50, 41, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(440, 50, 41, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.comboBox_6 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_6.setGeometry(QtCore.QRect(360, 20, 61, 22))
        self.comboBox_6.setProperty("currentText", _fromUtf8(""))
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.setItemText(0, _fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_8 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_8.setGeometry(QtCore.QRect(500, 20, 61, 22))
        self.comboBox_8.setProperty("currentText", _fromUtf8(""))
        self.comboBox_8.setObjectName(_fromUtf8("comboBox_8"))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.setItemText(0, _fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_10 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_10.setGeometry(QtCore.QRect(640, 20, 61, 22))
        self.comboBox_10.setProperty("currentText", _fromUtf8(""))
        self.comboBox_10.setObjectName(_fromUtf8("comboBox_10"))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.setItemText(0, _fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_12 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_12.setGeometry(QtCore.QRect(780, 20, 61, 22))
        self.comboBox_12.setProperty("currentText", _fromUtf8(""))
        self.comboBox_12.setObjectName(_fromUtf8("comboBox_12"))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.setItemText(0, _fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_2 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_2.setGeometry(QtCore.QRect(80, 20, 61, 22))
        self.comboBox_2.setProperty("currentText", _fromUtf8(""))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.setItemText(0, _fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_3 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_3.setGeometry(QtCore.QRect(150, 20, 61, 22))
        self.comboBox_3.setProperty("currentText", _fromUtf8(""))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.setItemText(0, _fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(300, 50, 41, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(90, 50, 41, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(650, 50, 41, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.comboBox_4 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_4.setGeometry(QtCore.QRect(220, 20, 61, 22))
        self.comboBox_4.setProperty("currentText", _fromUtf8(""))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.setItemText(0, _fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_1 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_1.setGeometry(QtCore.QRect(10, 20, 61, 22))
        self.comboBox_1.setProperty("currentText", _fromUtf8(""))
        self.comboBox_1.setObjectName(_fromUtf8("comboBox_1"))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.setItemText(0, _fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(720, 50, 41, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.comboBox_5 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_5.setGeometry(QtCore.QRect(290, 20, 61, 22))
        self.comboBox_5.setProperty("currentText", _fromUtf8(""))
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.setItemText(0, _fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(370, 50, 41, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.comboBox_9 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_9.setGeometry(QtCore.QRect(570, 20, 61, 22))
        self.comboBox_9.setProperty("currentText", _fromUtf8(""))
        self.comboBox_9.setObjectName(_fromUtf8("comboBox_9"))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.setItemText(0, _fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(510, 50, 41, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 50, 41, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(160, 50, 41, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(580, 50, 41, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(230, 50, 41, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.comboBox_11 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_11.setGeometry(QtCore.QRect(710, 20, 61, 22))
        self.comboBox_11.setProperty("currentText", _fromUtf8(""))
        self.comboBox_11.setObjectName(_fromUtf8("comboBox_11"))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.setItemText(0, _fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_7 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_7.setGeometry(QtCore.QRect(430, 20, 61, 22))
        self.comboBox_7.setProperty("currentText", _fromUtf8(""))
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.setItemText(0, _fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(740, 410, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Twelve-tone serialism generator", None))
        self.serie_properties.setTitle(_translate("MainWindow", "Generation properties", None))
        self.label_5.setText(_translate("MainWindow", "Half-tones", None))
        self.min_interval_label.setText(_translate("MainWindow", "Min interval:", None))
        self.max_interval_label.setText(_translate("MainWindow", "Max interval:", None))
        self.label_2.setText(_translate("MainWindow", "Half-tones", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Serie base", None))
        self.label_18.setText(_translate("MainWindow", "Note 12", None))
        self.label_13.setText(_translate("MainWindow", "Note 7", None))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "C", None))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "C#/Db", None))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "D", None))
        self.comboBox_6.setItemText(4, _translate("MainWindow", "D#/Eb", None))
        self.comboBox_6.setItemText(5, _translate("MainWindow", "E", None))
        self.comboBox_6.setItemText(6, _translate("MainWindow", "F", None))
        self.comboBox_6.setItemText(7, _translate("MainWindow", "F#/Gb", None))
        self.comboBox_6.setItemText(8, _translate("MainWindow", "G", None))
        self.comboBox_6.setItemText(9, _translate("MainWindow", "G#/Ab", None))
        self.comboBox_6.setItemText(10, _translate("MainWindow", "A", None))
        self.comboBox_6.setItemText(11, _translate("MainWindow", "A#/Bb", None))
        self.comboBox_6.setItemText(12, _translate("MainWindow", "B", None))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "C", None))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "C#/Db", None))
        self.comboBox_8.setItemText(3, _translate("MainWindow", "D", None))
        self.comboBox_8.setItemText(4, _translate("MainWindow", "D#/Eb", None))
        self.comboBox_8.setItemText(5, _translate("MainWindow", "E", None))
        self.comboBox_8.setItemText(6, _translate("MainWindow", "F", None))
        self.comboBox_8.setItemText(7, _translate("MainWindow", "F#/Gb", None))
        self.comboBox_8.setItemText(8, _translate("MainWindow", "G", None))
        self.comboBox_8.setItemText(9, _translate("MainWindow", "G#/Ab", None))
        self.comboBox_8.setItemText(10, _translate("MainWindow", "A", None))
        self.comboBox_8.setItemText(11, _translate("MainWindow", "A#/Bb", None))
        self.comboBox_8.setItemText(12, _translate("MainWindow", "B", None))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "C", None))
        self.comboBox_10.setItemText(2, _translate("MainWindow", "C#/Db", None))
        self.comboBox_10.setItemText(3, _translate("MainWindow", "D", None))
        self.comboBox_10.setItemText(4, _translate("MainWindow", "D#/Eb", None))
        self.comboBox_10.setItemText(5, _translate("MainWindow", "E", None))
        self.comboBox_10.setItemText(6, _translate("MainWindow", "F", None))
        self.comboBox_10.setItemText(7, _translate("MainWindow", "F#/Gb", None))
        self.comboBox_10.setItemText(8, _translate("MainWindow", "G", None))
        self.comboBox_10.setItemText(9, _translate("MainWindow", "G#/Ab", None))
        self.comboBox_10.setItemText(10, _translate("MainWindow", "A", None))
        self.comboBox_10.setItemText(11, _translate("MainWindow", "A#/Bb", None))
        self.comboBox_10.setItemText(12, _translate("MainWindow", "B", None))
        self.comboBox_12.setItemText(1, _translate("MainWindow", "C", None))
        self.comboBox_12.setItemText(2, _translate("MainWindow", "C#/Db", None))
        self.comboBox_12.setItemText(3, _translate("MainWindow", "D", None))
        self.comboBox_12.setItemText(4, _translate("MainWindow", "D#/Eb", None))
        self.comboBox_12.setItemText(5, _translate("MainWindow", "E", None))
        self.comboBox_12.setItemText(6, _translate("MainWindow", "F", None))
        self.comboBox_12.setItemText(7, _translate("MainWindow", "F#/Gb", None))
        self.comboBox_12.setItemText(8, _translate("MainWindow", "G", None))
        self.comboBox_12.setItemText(9, _translate("MainWindow", "G#/Ab", None))
        self.comboBox_12.setItemText(10, _translate("MainWindow", "A", None))
        self.comboBox_12.setItemText(11, _translate("MainWindow", "A#/Bb", None))
        self.comboBox_12.setItemText(12, _translate("MainWindow", "B", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "C", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "C#/Db", None))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "D", None))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "D#/Eb", None))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "E", None))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "F", None))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "F#/Gb", None))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "G", None))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "G#/Ab", None))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "A", None))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "A#/Bb", None))
        self.comboBox_2.setItemText(12, _translate("MainWindow", "B", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "C", None))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "C#/Db", None))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "D", None))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "D#/Eb", None))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "E", None))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "F", None))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "F#/Gb", None))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "G", None))
        self.comboBox_3.setItemText(9, _translate("MainWindow", "G#/Ab", None))
        self.comboBox_3.setItemText(10, _translate("MainWindow", "A", None))
        self.comboBox_3.setItemText(11, _translate("MainWindow", "A#/Bb", None))
        self.comboBox_3.setItemText(12, _translate("MainWindow", "B", None))
        self.label_11.setText(_translate("MainWindow", "Note 5", None))
        self.label_8.setText(_translate("MainWindow", "Note 2", None))
        self.label_16.setText(_translate("MainWindow", "Note 10", None))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "C", None))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "C#/Db", None))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "D", None))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "D#/Eb", None))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "E", None))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "F", None))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "F#/Gb", None))
        self.comboBox_4.setItemText(8, _translate("MainWindow", "G", None))
        self.comboBox_4.setItemText(9, _translate("MainWindow", "G#/Ab", None))
        self.comboBox_4.setItemText(10, _translate("MainWindow", "A", None))
        self.comboBox_4.setItemText(11, _translate("MainWindow", "A#/Bb", None))
        self.comboBox_4.setItemText(12, _translate("MainWindow", "B", None))
        self.comboBox_1.setItemText(1, _translate("MainWindow", "C", None))
        self.comboBox_1.setItemText(2, _translate("MainWindow", "C#/Db", None))
        self.comboBox_1.setItemText(3, _translate("MainWindow", "D", None))
        self.comboBox_1.setItemText(4, _translate("MainWindow", "D#/Eb", None))
        self.comboBox_1.setItemText(5, _translate("MainWindow", "E", None))
        self.comboBox_1.setItemText(6, _translate("MainWindow", "F", None))
        self.comboBox_1.setItemText(7, _translate("MainWindow", "F#/Gb", None))
        self.comboBox_1.setItemText(8, _translate("MainWindow", "G", None))
        self.comboBox_1.setItemText(9, _translate("MainWindow", "G#/Ab", None))
        self.comboBox_1.setItemText(10, _translate("MainWindow", "A", None))
        self.comboBox_1.setItemText(11, _translate("MainWindow", "A#/Bb", None))
        self.comboBox_1.setItemText(12, _translate("MainWindow", "B", None))
        self.label_17.setText(_translate("MainWindow", "Note 11", None))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "C", None))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "C#/Db", None))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "D", None))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "D#/Eb", None))
        self.comboBox_5.setItemText(5, _translate("MainWindow", "E", None))
        self.comboBox_5.setItemText(6, _translate("MainWindow", "F", None))
        self.comboBox_5.setItemText(7, _translate("MainWindow", "F#/Gb", None))
        self.comboBox_5.setItemText(8, _translate("MainWindow", "G", None))
        self.comboBox_5.setItemText(9, _translate("MainWindow", "G#/Ab", None))
        self.comboBox_5.setItemText(10, _translate("MainWindow", "A", None))
        self.comboBox_5.setItemText(11, _translate("MainWindow", "A#/Bb", None))
        self.comboBox_5.setItemText(12, _translate("MainWindow", "B", None))
        self.label_12.setText(_translate("MainWindow", "Note 6", None))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "C", None))
        self.comboBox_9.setItemText(2, _translate("MainWindow", "C#/Db", None))
        self.comboBox_9.setItemText(3, _translate("MainWindow", "D", None))
        self.comboBox_9.setItemText(4, _translate("MainWindow", "D#/Eb", None))
        self.comboBox_9.setItemText(5, _translate("MainWindow", "E", None))
        self.comboBox_9.setItemText(6, _translate("MainWindow", "F", None))
        self.comboBox_9.setItemText(7, _translate("MainWindow", "F#/Gb", None))
        self.comboBox_9.setItemText(8, _translate("MainWindow", "G", None))
        self.comboBox_9.setItemText(9, _translate("MainWindow", "G#/Ab", None))
        self.comboBox_9.setItemText(10, _translate("MainWindow", "A", None))
        self.comboBox_9.setItemText(11, _translate("MainWindow", "A#/Bb", None))
        self.comboBox_9.setItemText(12, _translate("MainWindow", "B", None))
        self.label_14.setText(_translate("MainWindow", "Note 8", None))
        self.label_7.setText(_translate("MainWindow", "Note 1", None))
        self.label_9.setText(_translate("MainWindow", "Note 3", None))
        self.label_15.setText(_translate("MainWindow", "Note 9", None))
        self.label_10.setText(_translate("MainWindow", "Note 4", None))
        self.comboBox_11.setItemText(1, _translate("MainWindow", "C", None))
        self.comboBox_11.setItemText(2, _translate("MainWindow", "C#/Db", None))
        self.comboBox_11.setItemText(3, _translate("MainWindow", "D", None))
        self.comboBox_11.setItemText(4, _translate("MainWindow", "D#/Eb", None))
        self.comboBox_11.setItemText(5, _translate("MainWindow", "E", None))
        self.comboBox_11.setItemText(6, _translate("MainWindow", "F", None))
        self.comboBox_11.setItemText(7, _translate("MainWindow", "F#/Gb", None))
        self.comboBox_11.setItemText(8, _translate("MainWindow", "G", None))
        self.comboBox_11.setItemText(9, _translate("MainWindow", "G#/Ab", None))
        self.comboBox_11.setItemText(10, _translate("MainWindow", "A", None))
        self.comboBox_11.setItemText(11, _translate("MainWindow", "A#/Bb", None))
        self.comboBox_11.setItemText(12, _translate("MainWindow", "B", None))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "C", None))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "C#/Db", None))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "D", None))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "D#/Eb", None))
        self.comboBox_7.setItemText(5, _translate("MainWindow", "E", None))
        self.comboBox_7.setItemText(6, _translate("MainWindow", "F", None))
        self.comboBox_7.setItemText(7, _translate("MainWindow", "F#/Gb", None))
        self.comboBox_7.setItemText(8, _translate("MainWindow", "G", None))
        self.comboBox_7.setItemText(9, _translate("MainWindow", "G#/Ab", None))
        self.comboBox_7.setItemText(10, _translate("MainWindow", "A", None))
        self.comboBox_7.setItemText(11, _translate("MainWindow", "A#/Bb", None))
        self.comboBox_7.setItemText(12, _translate("MainWindow", "B", None))
        self.pushButton.setText(_translate("MainWindow", "Apply", None))

