# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RuleTranslator.ui'
#
# Created: Wed Jun 11 15:42:30 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(929, 570)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 20, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.serie_properties = QtGui.QGroupBox(self.centralwidget)
        self.serie_properties.setGeometry(QtCore.QRect(40, 50, 291, 151))
        self.serie_properties.setObjectName(_fromUtf8("serie_properties"))
        self.label_5 = QtGui.QLabel(self.serie_properties)
        self.label_5.setGeometry(QtCore.QRect(181, 83, 61, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.min_interval_label = QtGui.QLabel(self.serie_properties)
        self.min_interval_label.setGeometry(QtCore.QRect(31, 53, 71, 16))
        self.min_interval_label.setObjectName(_fromUtf8("min_interval_label"))
        self.max_interval_label = QtGui.QLabel(self.serie_properties)
        self.max_interval_label.setGeometry(QtCore.QRect(31, 83, 71, 16))
        self.max_interval_label.setObjectName(_fromUtf8("max_interval_label"))
        self.max_interval = QtGui.QSpinBox(self.serie_properties)
        self.max_interval.setGeometry(QtCore.QRect(130, 80, 42, 22))
        self.max_interval.setMinimum(1)
        self.max_interval.setMaximum(7)
        self.max_interval.setProperty("value", 7)
        self.max_interval.setObjectName(_fromUtf8("max_interval"))
        self.label_2 = QtGui.QLabel(self.serie_properties)
        self.label_2.setGeometry(QtCore.QRect(181, 53, 61, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.min_interval = QtGui.QSpinBox(self.serie_properties)
        self.min_interval.setGeometry(QtCore.QRect(130, 50, 42, 22))
        self.min_interval.setMinimum(1)
        self.min_interval.setMaximum(5)
        self.min_interval.setObjectName(_fromUtf8("min_interval"))
        self.serieBase = QtGui.QGroupBox(self.centralwidget)
        self.serieBase.setGeometry(QtCore.QRect(40, 210, 861, 91))
        self.serieBase.setObjectName(_fromUtf8("serieBase"))
        self.label_18 = QtGui.QLabel(self.serieBase)
        self.label_18.setGeometry(QtCore.QRect(790, 50, 41, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_13 = QtGui.QLabel(self.serieBase)
        self.label_13.setGeometry(QtCore.QRect(440, 50, 41, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.comboBox_6 = QtGui.QComboBox(self.serieBase)
        self.comboBox_6.setGeometry(QtCore.QRect(360, 20, 61, 22))
        self.comboBox_6.setProperty("currentText", _fromUtf8(""))
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.setItemText(0, _fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_8 = QtGui.QComboBox(self.serieBase)
        self.comboBox_8.setGeometry(QtCore.QRect(500, 20, 61, 22))
        self.comboBox_8.setProperty("currentText", _fromUtf8(""))
        self.comboBox_8.setObjectName(_fromUtf8("comboBox_8"))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.setItemText(0, _fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_10 = QtGui.QComboBox(self.serieBase)
        self.comboBox_10.setGeometry(QtCore.QRect(640, 20, 61, 22))
        self.comboBox_10.setProperty("currentText", _fromUtf8(""))
        self.comboBox_10.setObjectName(_fromUtf8("comboBox_10"))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.setItemText(0, _fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_12 = QtGui.QComboBox(self.serieBase)
        self.comboBox_12.setGeometry(QtCore.QRect(780, 20, 61, 22))
        self.comboBox_12.setProperty("currentText", _fromUtf8(""))
        self.comboBox_12.setObjectName(_fromUtf8("comboBox_12"))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.setItemText(0, _fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_2 = QtGui.QComboBox(self.serieBase)
        self.comboBox_2.setGeometry(QtCore.QRect(80, 20, 61, 22))
        self.comboBox_2.setProperty("currentText", _fromUtf8(""))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.setItemText(0, _fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_3 = QtGui.QComboBox(self.serieBase)
        self.comboBox_3.setGeometry(QtCore.QRect(150, 20, 61, 22))
        self.comboBox_3.setProperty("currentText", _fromUtf8(""))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.setItemText(0, _fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.label_11 = QtGui.QLabel(self.serieBase)
        self.label_11.setGeometry(QtCore.QRect(300, 50, 41, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_8 = QtGui.QLabel(self.serieBase)
        self.label_8.setGeometry(QtCore.QRect(90, 50, 41, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_16 = QtGui.QLabel(self.serieBase)
        self.label_16.setGeometry(QtCore.QRect(650, 50, 41, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.comboBox_4 = QtGui.QComboBox(self.serieBase)
        self.comboBox_4.setGeometry(QtCore.QRect(220, 20, 61, 22))
        self.comboBox_4.setProperty("currentText", _fromUtf8(""))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.setItemText(0, _fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_1 = QtGui.QComboBox(self.serieBase)
        self.comboBox_1.setGeometry(QtCore.QRect(10, 20, 61, 22))
        self.comboBox_1.setProperty("currentText", _fromUtf8(""))
        self.comboBox_1.setObjectName(_fromUtf8("comboBox_1"))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.setItemText(0, _fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.label_17 = QtGui.QLabel(self.serieBase)
        self.label_17.setGeometry(QtCore.QRect(720, 50, 41, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.comboBox_5 = QtGui.QComboBox(self.serieBase)
        self.comboBox_5.setGeometry(QtCore.QRect(290, 20, 61, 22))
        self.comboBox_5.setProperty("currentText", _fromUtf8(""))
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.setItemText(0, _fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.label_12 = QtGui.QLabel(self.serieBase)
        self.label_12.setGeometry(QtCore.QRect(370, 50, 41, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.comboBox_9 = QtGui.QComboBox(self.serieBase)
        self.comboBox_9.setGeometry(QtCore.QRect(570, 20, 61, 22))
        self.comboBox_9.setProperty("currentText", _fromUtf8(""))
        self.comboBox_9.setObjectName(_fromUtf8("comboBox_9"))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.setItemText(0, _fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.label_14 = QtGui.QLabel(self.serieBase)
        self.label_14.setGeometry(QtCore.QRect(510, 50, 41, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_7 = QtGui.QLabel(self.serieBase)
        self.label_7.setGeometry(QtCore.QRect(20, 50, 41, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_9 = QtGui.QLabel(self.serieBase)
        self.label_9.setGeometry(QtCore.QRect(160, 50, 41, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_15 = QtGui.QLabel(self.serieBase)
        self.label_15.setGeometry(QtCore.QRect(580, 50, 41, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_10 = QtGui.QLabel(self.serieBase)
        self.label_10.setGeometry(QtCore.QRect(230, 50, 41, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.comboBox_11 = QtGui.QComboBox(self.serieBase)
        self.comboBox_11.setGeometry(QtCore.QRect(710, 20, 61, 22))
        self.comboBox_11.setProperty("currentText", _fromUtf8(""))
        self.comboBox_11.setObjectName(_fromUtf8("comboBox_11"))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.setItemText(0, _fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_7 = QtGui.QComboBox(self.serieBase)
        self.comboBox_7.setGeometry(QtCore.QRect(430, 20, 61, 22))
        self.comboBox_7.setProperty("currentText", _fromUtf8(""))
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.setItemText(0, _fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.scoreProperties = QtGui.QGroupBox(self.centralwidget)
        self.scoreProperties.setGeometry(QtCore.QRect(40, 310, 761, 201))
        self.scoreProperties.setObjectName(_fromUtf8("scoreProperties"))
        self.percentajeNotes = QtGui.QSpinBox(self.scoreProperties)
        self.percentajeNotes.setGeometry(QtCore.QRect(260, 57, 42, 22))
        self.percentajeNotes.setMinimum(1)
        self.percentajeNotes.setMaximum(100)
        self.percentajeNotes.setProperty("value", 20)
        self.percentajeNotes.setObjectName(_fromUtf8("percentajeNotes"))
        self.percentNotes_label = QtGui.QLabel(self.scoreProperties)
        self.percentNotes_label.setGeometry(QtCore.QRect(30, 60, 231, 16))
        self.percentNotes_label.setObjectName(_fromUtf8("percentNotes_label"))
        self.seriesPerVoice = QtGui.QSpinBox(self.scoreProperties)
        self.seriesPerVoice.setGeometry(QtCore.QRect(260, 20, 42, 22))
        self.seriesPerVoice.setMinimum(1)
        self.seriesPerVoice.setMaximum(100)
        self.seriesPerVoice.setProperty("value", 3)
        self.seriesPerVoice.setObjectName(_fromUtf8("seriesPerVoice"))
        self.numVoice_label = QtGui.QLabel(self.scoreProperties)
        self.numVoice_label.setGeometry(QtCore.QRect(30, 26, 101, 16))
        self.numVoice_label.setObjectName(_fromUtf8("numVoice_label"))
        self.thresholdOctaves = QtGui.QSpinBox(self.scoreProperties)
        self.thresholdOctaves.setGeometry(QtCore.QRect(260, 93, 42, 22))
        self.thresholdOctaves.setMinimum(1)
        self.thresholdOctaves.setMaximum(1000)
        self.thresholdOctaves.setProperty("value", 50)
        self.thresholdOctaves.setObjectName(_fromUtf8("thresholdOctaves"))
        self.octaveJump_label = QtGui.QLabel(self.scoreProperties)
        self.octaveJump_label.setGeometry(QtCore.QRect(30, 98, 141, 16))
        self.octaveJump_label.setObjectName(_fromUtf8("octaveJump_label"))
        self.minMaxOctave_label = QtGui.QLabel(self.scoreProperties)
        self.minMaxOctave_label.setGeometry(QtCore.QRect(30, 135, 161, 16))
        self.minMaxOctave_label.setObjectName(_fromUtf8("minMaxOctave_label"))
        self.minOctave = QtGui.QSpinBox(self.scoreProperties)
        self.minOctave.setGeometry(QtCore.QRect(260, 130, 42, 22))
        self.minOctave.setMinimum(2)
        self.minOctave.setMaximum(4)
        self.minOctave.setProperty("value", 2)
        self.minOctave.setObjectName(_fromUtf8("minOctave"))
        self.maxDivision_label = QtGui.QLabel(self.scoreProperties)
        self.maxDivision_label.setGeometry(QtCore.QRect(420, 98, 141, 16))
        self.maxDivision_label.setObjectName(_fromUtf8("maxDivision_label"))
        self.reRatios = QtGui.QSpinBox(self.scoreProperties)
        self.reRatios.setGeometry(QtCore.QRect(650, 57, 42, 22))
        self.reRatios.setMinimum(1)
        self.reRatios.setMaximum(100)
        self.reRatios.setProperty("value", 1)
        self.reRatios.setObjectName(_fromUtf8("reRatios"))
        self.measure_label = QtGui.QLabel(self.scoreProperties)
        self.measure_label.setGeometry(QtCore.QRect(420, 27, 101, 16))
        self.measure_label.setObjectName(_fromUtf8("measure_label"))
        self.ratios_label = QtGui.QLabel(self.scoreProperties)
        self.ratios_label.setGeometry(QtCore.QRect(420, 60, 231, 16))
        self.ratios_label.setObjectName(_fromUtf8("ratios_label"))
        self.maxDivision = QtGui.QSpinBox(self.scoreProperties)
        self.maxDivision.setGeometry(QtCore.QRect(650, 93, 42, 22))
        self.maxDivision.setMinimum(1)
        self.maxDivision.setMaximum(16)
        self.maxDivision.setSingleStep(1)
        self.maxDivision.setProperty("value", 8)
        self.maxDivision.setObjectName(_fromUtf8("maxDivision"))
        self.figureTempo_label = QtGui.QLabel(self.scoreProperties)
        self.figureTempo_label.setGeometry(QtCore.QRect(420, 124, 201, 41))
        self.figureTempo_label.setObjectName(_fromUtf8("figureTempo_label"))
        self.maxFigure = QtGui.QSpinBox(self.scoreProperties)
        self.maxFigure.setGeometry(QtCore.QRect(650, 130, 42, 22))
        self.maxFigure.setMinimum(1)
        self.maxFigure.setMaximum(64)
        self.maxFigure.setProperty("value", 1)
        self.maxFigure.setObjectName(_fromUtf8("maxFigure"))
        self.maxOctave = QtGui.QSpinBox(self.scoreProperties)
        self.maxOctave.setGeometry(QtCore.QRect(310, 130, 42, 22))
        self.maxOctave.setMinimum(2)
        self.maxOctave.setMaximum(4)
        self.maxOctave.setProperty("value", 4)
        self.maxOctave.setObjectName(_fromUtf8("maxOctave"))
        self.measure1 = QtGui.QComboBox(self.scoreProperties)
        self.measure1.setGeometry(QtCore.QRect(650, 20, 41, 22))
        self.measure1.setObjectName(_fromUtf8("measure1"))
        self.measure1.addItem(_fromUtf8(""))
        self.measure1.addItem(_fromUtf8(""))
        self.measure1.addItem(_fromUtf8(""))
        self.measure1.addItem(_fromUtf8(""))
        self.measure1.addItem(_fromUtf8(""))
        self.measure1.addItem(_fromUtf8(""))
        self.measure2 = QtGui.QComboBox(self.scoreProperties)
        self.measure2.setGeometry(QtCore.QRect(690, 20, 41, 22))
        self.measure2.setObjectName(_fromUtf8("measure2"))
        self.measure2.addItem(_fromUtf8(""))
        self.measure2.addItem(_fromUtf8(""))
        self.measure2.addItem(_fromUtf8(""))
        self.measure2.addItem(_fromUtf8(""))
        self.measure2.addItem(_fromUtf8(""))
        self.measure2.addItem(_fromUtf8(""))
        self.reRatios2 = QtGui.QSpinBox(self.scoreProperties)
        self.reRatios2.setGeometry(QtCore.QRect(690, 57, 42, 22))
        self.reRatios2.setMinimum(1)
        self.reRatios2.setMaximum(100)
        self.reRatios2.setProperty("value", 4)
        self.reRatios2.setObjectName(_fromUtf8("reRatios2"))
        self.minFigure = QtGui.QSpinBox(self.scoreProperties)
        self.minFigure.setGeometry(QtCore.QRect(690, 130, 42, 22))
        self.minFigure.setMinimum(1)
        self.minFigure.setMaximum(64)
        self.minFigure.setProperty("value", 16)
        self.minFigure.setObjectName(_fromUtf8("minFigure"))
        self.voices_label = QtGui.QLabel(self.scoreProperties)
        self.voices_label.setGeometry(QtCore.QRect(30, 172, 161, 16))
        self.voices_label.setObjectName(_fromUtf8("voices_label"))
        self.voices = QtGui.QSpinBox(self.scoreProperties)
        self.voices.setGeometry(QtCore.QRect(260, 168, 42, 22))
        self.voices.setMinimum(1)
        self.voices.setMaximum(100)
        self.voices.setProperty("value", 2)
        self.voices.setObjectName(_fromUtf8("voices"))
        self.transpose_label = QtGui.QLabel(self.scoreProperties)
        self.transpose_label.setGeometry(QtCore.QRect(420, 174, 161, 16))
        self.transpose_label.setObjectName(_fromUtf8("transpose_label"))
        self.transpose = QtGui.QSpinBox(self.scoreProperties)
        self.transpose.setGeometry(QtCore.QRect(650, 170, 42, 22))
        self.transpose.setMinimum(1)
        self.transpose.setMaximum(1000)
        self.transpose.setProperty("value", 1)
        self.transpose.setObjectName(_fromUtf8("transpose"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(790, 520, 101, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.measure1.setCurrentIndex(2)
        self.measure2.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Twelve-tone serialism generator", None))
        self.serie_properties.setTitle(_translate("MainWindow", "Series generation properties", None))
        self.label_5.setText(_translate("MainWindow", "Half-tones", None))
        self.min_interval_label.setText(_translate("MainWindow", "Min interval:", None))
        self.max_interval_label.setText(_translate("MainWindow", "Max interval:", None))
        self.label_2.setText(_translate("MainWindow", "Half-tones", None))
        self.serieBase.setTitle(_translate("MainWindow", "Series base", None))
        self.label_18.setText(_translate("MainWindow", "Note 12", None))
        self.label_13.setText(_translate("MainWindow", "Note 7", None))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "C", None))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "C#/Db", None))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "D", None))
        self.comboBox_6.setItemText(4, _translate("MainWindow", "D#/Eb", None))
        self.comboBox_6.setItemText(5, _translate("MainWindow", "E", None))
        self.comboBox_6.setItemText(6, _translate("MainWindow", "F", None))
        self.comboBox_6.setItemText(7, _translate("MainWindow", "F#/Gb", None))
        self.comboBox_6.setItemText(8, _translate("MainWindow", "G", None))
        self.comboBox_6.setItemText(9, _translate("MainWindow", "G#/Ab", None))
        self.comboBox_6.setItemText(10, _translate("MainWindow", "A", None))
        self.comboBox_6.setItemText(11, _translate("MainWindow", "A#/Bb", None))
        self.comboBox_6.setItemText(12, _translate("MainWindow", "B", None))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "C", None))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "C#/Db", None))
        self.comboBox_8.setItemText(3, _translate("MainWindow", "D", None))
        self.comboBox_8.setItemText(4, _translate("MainWindow", "D#/Eb", None))
        self.comboBox_8.setItemText(5, _translate("MainWindow", "E", None))
        self.comboBox_8.setItemText(6, _translate("MainWindow", "F", None))
        self.comboBox_8.setItemText(7, _translate("MainWindow", "F#/Gb", None))
        self.comboBox_8.setItemText(8, _translate("MainWindow", "G", None))
        self.comboBox_8.setItemText(9, _translate("MainWindow", "G#/Ab", None))
        self.comboBox_8.setItemText(10, _translate("MainWindow", "A", None))
        self.comboBox_8.setItemText(11, _translate("MainWindow", "A#/Bb", None))
        self.comboBox_8.setItemText(12, _translate("MainWindow", "B", None))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "C", None))
        self.comboBox_10.setItemText(2, _translate("MainWindow", "C#/Db", None))
        self.comboBox_10.setItemText(3, _translate("MainWindow", "D", None))
        self.comboBox_10.setItemText(4, _translate("MainWindow", "D#/Eb", None))
        self.comboBox_10.setItemText(5, _translate("MainWindow", "E", None))
        self.comboBox_10.setItemText(6, _translate("MainWindow", "F", None))
        self.comboBox_10.setItemText(7, _translate("MainWindow", "F#/Gb", None))
        self.comboBox_10.setItemText(8, _translate("MainWindow", "G", None))
        self.comboBox_10.setItemText(9, _translate("MainWindow", "G#/Ab", None))
        self.comboBox_10.setItemText(10, _translate("MainWindow", "A", None))
        self.comboBox_10.setItemText(11, _translate("MainWindow", "A#/Bb", None))
        self.comboBox_10.setItemText(12, _translate("MainWindow", "B", None))
        self.comboBox_12.setItemText(1, _translate("MainWindow", "C", None))
        self.comboBox_12.setItemText(2, _translate("MainWindow", "C#/Db", None))
        self.comboBox_12.setItemText(3, _translate("MainWindow", "D", None))
        self.comboBox_12.setItemText(4, _translate("MainWindow", "D#/Eb", None))
        self.comboBox_12.setItemText(5, _translate("MainWindow", "E", None))
        self.comboBox_12.setItemText(6, _translate("MainWindow", "F", None))
        self.comboBox_12.setItemText(7, _translate("MainWindow", "F#/Gb", None))
        self.comboBox_12.setItemText(8, _translate("MainWindow", "G", None))
        self.comboBox_12.setItemText(9, _translate("MainWindow", "G#/Ab", None))
        self.comboBox_12.setItemText(10, _translate("MainWindow", "A", None))
        self.comboBox_12.setItemText(11, _translate("MainWindow", "A#/Bb", None))
        self.comboBox_12.setItemText(12, _translate("MainWindow", "B", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "C", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "C#/Db", None))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "D", None))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "D#/Eb", None))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "E", None))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "F", None))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "F#/Gb", None))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "G", None))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "G#/Ab", None))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "A", None))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "A#/Bb", None))
        self.comboBox_2.setItemText(12, _translate("MainWindow", "B", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "C", None))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "C#/Db", None))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "D", None))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "D#/Eb", None))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "E", None))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "F", None))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "F#/Gb", None))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "G", None))
        self.comboBox_3.setItemText(9, _translate("MainWindow", "G#/Ab", None))
        self.comboBox_3.setItemText(10, _translate("MainWindow", "A", None))
        self.comboBox_3.setItemText(11, _translate("MainWindow", "A#/Bb", None))
        self.comboBox_3.setItemText(12, _translate("MainWindow", "B", None))
        self.label_11.setText(_translate("MainWindow", "Note 5", None))
        self.label_8.setText(_translate("MainWindow", "Note 2", None))
        self.label_16.setText(_translate("MainWindow", "Note 10", None))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "C", None))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "C#/Db", None))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "D", None))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "D#/Eb", None))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "E", None))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "F", None))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "F#/Gb", None))
        self.comboBox_4.setItemText(8, _translate("MainWindow", "G", None))
        self.comboBox_4.setItemText(9, _translate("MainWindow", "G#/Ab", None))
        self.comboBox_4.setItemText(10, _translate("MainWindow", "A", None))
        self.comboBox_4.setItemText(11, _translate("MainWindow", "A#/Bb", None))
        self.comboBox_4.setItemText(12, _translate("MainWindow", "B", None))
        self.comboBox_1.setItemText(1, _translate("MainWindow", "C", None))
        self.comboBox_1.setItemText(2, _translate("MainWindow", "C#/Db", None))
        self.comboBox_1.setItemText(3, _translate("MainWindow", "D", None))
        self.comboBox_1.setItemText(4, _translate("MainWindow", "D#/Eb", None))
        self.comboBox_1.setItemText(5, _translate("MainWindow", "E", None))
        self.comboBox_1.setItemText(6, _translate("MainWindow", "F", None))
        self.comboBox_1.setItemText(7, _translate("MainWindow", "F#/Gb", None))
        self.comboBox_1.setItemText(8, _translate("MainWindow", "G", None))
        self.comboBox_1.setItemText(9, _translate("MainWindow", "G#/Ab", None))
        self.comboBox_1.setItemText(10, _translate("MainWindow", "A", None))
        self.comboBox_1.setItemText(11, _translate("MainWindow", "A#/Bb", None))
        self.comboBox_1.setItemText(12, _translate("MainWindow", "B", None))
        self.label_17.setText(_translate("MainWindow", "Note 11", None))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "C", None))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "C#/Db", None))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "D", None))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "D#/Eb", None))
        self.comboBox_5.setItemText(5, _translate("MainWindow", "E", None))
        self.comboBox_5.setItemText(6, _translate("MainWindow", "F", None))
        self.comboBox_5.setItemText(7, _translate("MainWindow", "F#/Gb", None))
        self.comboBox_5.setItemText(8, _translate("MainWindow", "G", None))
        self.comboBox_5.setItemText(9, _translate("MainWindow", "G#/Ab", None))
        self.comboBox_5.setItemText(10, _translate("MainWindow", "A", None))
        self.comboBox_5.setItemText(11, _translate("MainWindow", "A#/Bb", None))
        self.comboBox_5.setItemText(12, _translate("MainWindow", "B", None))
        self.label_12.setText(_translate("MainWindow", "Note 6", None))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "C", None))
        self.comboBox_9.setItemText(2, _translate("MainWindow", "C#/Db", None))
        self.comboBox_9.setItemText(3, _translate("MainWindow", "D", None))
        self.comboBox_9.setItemText(4, _translate("MainWindow", "D#/Eb", None))
        self.comboBox_9.setItemText(5, _translate("MainWindow", "E", None))
        self.comboBox_9.setItemText(6, _translate("MainWindow", "F", None))
        self.comboBox_9.setItemText(7, _translate("MainWindow", "F#/Gb", None))
        self.comboBox_9.setItemText(8, _translate("MainWindow", "G", None))
        self.comboBox_9.setItemText(9, _translate("MainWindow", "G#/Ab", None))
        self.comboBox_9.setItemText(10, _translate("MainWindow", "A", None))
        self.comboBox_9.setItemText(11, _translate("MainWindow", "A#/Bb", None))
        self.comboBox_9.setItemText(12, _translate("MainWindow", "B", None))
        self.label_14.setText(_translate("MainWindow", "Note 8", None))
        self.label_7.setText(_translate("MainWindow", "Note 1", None))
        self.label_9.setText(_translate("MainWindow", "Note 3", None))
        self.label_15.setText(_translate("MainWindow", "Note 9", None))
        self.label_10.setText(_translate("MainWindow", "Note 4", None))
        self.comboBox_11.setItemText(1, _translate("MainWindow", "C", None))
        self.comboBox_11.setItemText(2, _translate("MainWindow", "C#/Db", None))
        self.comboBox_11.setItemText(3, _translate("MainWindow", "D", None))
        self.comboBox_11.setItemText(4, _translate("MainWindow", "D#/Eb", None))
        self.comboBox_11.setItemText(5, _translate("MainWindow", "E", None))
        self.comboBox_11.setItemText(6, _translate("MainWindow", "F", None))
        self.comboBox_11.setItemText(7, _translate("MainWindow", "F#/Gb", None))
        self.comboBox_11.setItemText(8, _translate("MainWindow", "G", None))
        self.comboBox_11.setItemText(9, _translate("MainWindow", "G#/Ab", None))
        self.comboBox_11.setItemText(10, _translate("MainWindow", "A", None))
        self.comboBox_11.setItemText(11, _translate("MainWindow", "A#/Bb", None))
        self.comboBox_11.setItemText(12, _translate("MainWindow", "B", None))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "C", None))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "C#/Db", None))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "D", None))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "D#/Eb", None))
        self.comboBox_7.setItemText(5, _translate("MainWindow", "E", None))
        self.comboBox_7.setItemText(6, _translate("MainWindow", "F", None))
        self.comboBox_7.setItemText(7, _translate("MainWindow", "F#/Gb", None))
        self.comboBox_7.setItemText(8, _translate("MainWindow", "G", None))
        self.comboBox_7.setItemText(9, _translate("MainWindow", "G#/Ab", None))
        self.comboBox_7.setItemText(10, _translate("MainWindow", "A", None))
        self.comboBox_7.setItemText(11, _translate("MainWindow", "A#/Bb", None))
        self.comboBox_7.setItemText(12, _translate("MainWindow", "B", None))
        self.scoreProperties.setTitle(_translate("MainWindow", "Score properties", None))
        self.percentNotes_label.setText(_translate("MainWindow", "Percentaje of notes (100-percentaje of rests)", None))
        self.numVoice_label.setText(_translate("MainWindow", "Series per voice", None))
        self.octaveJump_label.setText(_translate("MainWindow", "Threshold for octave jumps", None))
        self.minMaxOctave_label.setText(_translate("MainWindow", "Min/Max octave (3 = C3 = Do3)", None))
        self.maxDivision_label.setText(_translate("MainWindow", "Maximum division", None))
        self.measure_label.setText(_translate("MainWindow", "Measure", None))
        self.ratios_label.setText(_translate("MainWindow", "Reduction and enlargement ratios", None))
        self.figureTempo_label.setText(_translate("MainWindow", "Max and min figure tempo generation \n"
"(for a r/e ratio of 2, 4 is a quarter note,\n"
"8 is a quaver)", None))
        self.measure1.setProperty("currentText", _translate("MainWindow", "4", None))
        self.measure1.setItemText(0, _translate("MainWindow", "1", None))
        self.measure1.setItemText(1, _translate("MainWindow", "2", None))
        self.measure1.setItemText(2, _translate("MainWindow", "4", None))
        self.measure1.setItemText(3, _translate("MainWindow", "8", None))
        self.measure1.setItemText(4, _translate("MainWindow", "16", None))
        self.measure1.setItemText(5, _translate("MainWindow", "32", None))
        self.measure2.setProperty("currentText", _translate("MainWindow", "4", None))
        self.measure2.setItemText(0, _translate("MainWindow", "1", None))
        self.measure2.setItemText(1, _translate("MainWindow", "2", None))
        self.measure2.setItemText(2, _translate("MainWindow", "4", None))
        self.measure2.setItemText(3, _translate("MainWindow", "8", None))
        self.measure2.setItemText(4, _translate("MainWindow", "16", None))
        self.measure2.setItemText(5, _translate("MainWindow", "32", None))
        self.voices_label.setText(_translate("MainWindow", "Num of voices", None))
        self.transpose_label.setText(_translate("MainWindow", "Transpose threshold", None))
        self.pushButton.setText(_translate("MainWindow", "Get Parameters", None))

