# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RuleTranslator.ui'
#
# Created: Thu Feb 13 20:43:53 2014
#      by: PyQt5 UI code generator 5.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(931, 487)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 40, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(775, 410, 81, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(70, 80, 291, 151))
        self.groupBox.setObjectName("groupBox")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(181, 83, 61, 16))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(31, 53, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(31, 83, 71, 16))
        self.label_3.setObjectName("label_3")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_2.setGeometry(QtCore.QRect(130, 80, 42, 22))
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(5)
        self.spinBox_2.setProperty("value", 5)
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(181, 53, 61, 16))
        self.label_2.setObjectName("label_2")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setGeometry(QtCore.QRect(130, 50, 42, 22))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(5)
        self.spinBox.setObjectName("spinBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 270, 861, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(790, 50, 41, 16))
        self.label_18.setObjectName("label_18")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(440, 50, 41, 16))
        self.label_13.setObjectName("label_13")
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_6.setGeometry(QtCore.QRect(360, 20, 61, 22))
        self.comboBox_6.setCurrentText("")
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.setItemText(0, "")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_8 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_8.setGeometry(QtCore.QRect(500, 20, 61, 22))
        self.comboBox_8.setCurrentText("")
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.setItemText(0, "")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_10 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_10.setGeometry(QtCore.QRect(640, 20, 61, 22))
        self.comboBox_10.setCurrentText("")
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.setItemText(0, "")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_12 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_12.setGeometry(QtCore.QRect(780, 20, 61, 22))
        self.comboBox_12.setCurrentText("")
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.setItemText(0, "")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setGeometry(QtCore.QRect(80, 20, 61, 22))
        self.comboBox_2.setCurrentText("")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_3.setGeometry(QtCore.QRect(150, 20, 61, 22))
        self.comboBox_3.setCurrentText("")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.setItemText(0, "")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(300, 50, 41, 16))
        self.label_11.setObjectName("label_11")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(90, 50, 41, 16))
        self.label_8.setObjectName("label_8")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(650, 50, 41, 16))
        self.label_16.setObjectName("label_16")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_4.setGeometry(QtCore.QRect(220, 20, 61, 22))
        self.comboBox_4.setCurrentText("")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.setItemText(0, "")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(10, 20, 61, 22))
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(720, 50, 41, 16))
        self.label_17.setObjectName("label_17")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_5.setGeometry(QtCore.QRect(290, 20, 61, 22))
        self.comboBox_5.setCurrentText("")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.setItemText(0, "")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(370, 50, 41, 16))
        self.label_12.setObjectName("label_12")
        self.comboBox_9 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_9.setGeometry(QtCore.QRect(570, 20, 61, 22))
        self.comboBox_9.setCurrentText("")
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.setItemText(0, "")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(510, 50, 41, 16))
        self.label_14.setObjectName("label_14")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 50, 41, 16))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(160, 50, 41, 16))
        self.label_9.setObjectName("label_9")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(580, 50, 41, 16))
        self.label_15.setObjectName("label_15")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(230, 50, 41, 16))
        self.label_10.setObjectName("label_10")
        self.comboBox_11 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_11.setGeometry(QtCore.QRect(710, 20, 61, 22))
        self.comboBox_11.setCurrentText("")
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.setItemText(0, "")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_7.setGeometry(QtCore.QRect(430, 20, 61, 22))
        self.comboBox_7.setCurrentText("")
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.setItemText(0, "")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Twelve-tone serialism generator"))
        self.groupBox.setTitle(_translate("MainWindow", "Generation properties"))
        self.label_5.setText(_translate("MainWindow", "Half-tones"))
        self.label_4.setText(_translate("MainWindow", "Min interval:"))
        self.label_3.setText(_translate("MainWindow", "Max interval:"))
        self.label_2.setText(_translate("MainWindow", "Half-tones"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Serie base"))
        self.label_18.setText(_translate("MainWindow", "Note 12"))
        self.label_13.setText(_translate("MainWindow", "Note 7"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "C"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "C#/Db"))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "D"))
        self.comboBox_6.setItemText(4, _translate("MainWindow", "D#/Eb"))
        self.comboBox_6.setItemText(5, _translate("MainWindow", "E"))
        self.comboBox_6.setItemText(6, _translate("MainWindow", "F"))
        self.comboBox_6.setItemText(7, _translate("MainWindow", "F#/Gb"))
        self.comboBox_6.setItemText(8, _translate("MainWindow", "G"))
        self.comboBox_6.setItemText(9, _translate("MainWindow", "G#/Ab"))
        self.comboBox_6.setItemText(10, _translate("MainWindow", "A"))
        self.comboBox_6.setItemText(11, _translate("MainWindow", "A#/Bb"))
        self.comboBox_6.setItemText(12, _translate("MainWindow", "B"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "C"))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "C#/Db"))
        self.comboBox_8.setItemText(3, _translate("MainWindow", "D"))
        self.comboBox_8.setItemText(4, _translate("MainWindow", "D#/Eb"))
        self.comboBox_8.setItemText(5, _translate("MainWindow", "E"))
        self.comboBox_8.setItemText(6, _translate("MainWindow", "F"))
        self.comboBox_8.setItemText(7, _translate("MainWindow", "F#/Gb"))
        self.comboBox_8.setItemText(8, _translate("MainWindow", "G"))
        self.comboBox_8.setItemText(9, _translate("MainWindow", "G#/Ab"))
        self.comboBox_8.setItemText(10, _translate("MainWindow", "A"))
        self.comboBox_8.setItemText(11, _translate("MainWindow", "A#/Bb"))
        self.comboBox_8.setItemText(12, _translate("MainWindow", "B"))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "C"))
        self.comboBox_10.setItemText(2, _translate("MainWindow", "C#/Db"))
        self.comboBox_10.setItemText(3, _translate("MainWindow", "D"))
        self.comboBox_10.setItemText(4, _translate("MainWindow", "D#/Eb"))
        self.comboBox_10.setItemText(5, _translate("MainWindow", "E"))
        self.comboBox_10.setItemText(6, _translate("MainWindow", "F"))
        self.comboBox_10.setItemText(7, _translate("MainWindow", "F#/Gb"))
        self.comboBox_10.setItemText(8, _translate("MainWindow", "G"))
        self.comboBox_10.setItemText(9, _translate("MainWindow", "G#/Ab"))
        self.comboBox_10.setItemText(10, _translate("MainWindow", "A"))
        self.comboBox_10.setItemText(11, _translate("MainWindow", "A#/Bb"))
        self.comboBox_10.setItemText(12, _translate("MainWindow", "B"))
        self.comboBox_12.setItemText(1, _translate("MainWindow", "C"))
        self.comboBox_12.setItemText(2, _translate("MainWindow", "C#/Db"))
        self.comboBox_12.setItemText(3, _translate("MainWindow", "D"))
        self.comboBox_12.setItemText(4, _translate("MainWindow", "D#/Eb"))
        self.comboBox_12.setItemText(5, _translate("MainWindow", "E"))
        self.comboBox_12.setItemText(6, _translate("MainWindow", "F"))
        self.comboBox_12.setItemText(7, _translate("MainWindow", "F#/Gb"))
        self.comboBox_12.setItemText(8, _translate("MainWindow", "G"))
        self.comboBox_12.setItemText(9, _translate("MainWindow", "G#/Ab"))
        self.comboBox_12.setItemText(10, _translate("MainWindow", "A"))
        self.comboBox_12.setItemText(11, _translate("MainWindow", "A#/Bb"))
        self.comboBox_12.setItemText(12, _translate("MainWindow", "B"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "C"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "C#/Db"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "D"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "D#/Eb"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "E"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "F"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "F#/Gb"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "G"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "G#/Ab"))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "A"))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "A#/Bb"))
        self.comboBox_2.setItemText(12, _translate("MainWindow", "B"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "C"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "C#/Db"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "D"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "D#/Eb"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "E"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "F"))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "F#/Gb"))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "G"))
        self.comboBox_3.setItemText(9, _translate("MainWindow", "G#/Ab"))
        self.comboBox_3.setItemText(10, _translate("MainWindow", "A"))
        self.comboBox_3.setItemText(11, _translate("MainWindow", "A#/Bb"))
        self.comboBox_3.setItemText(12, _translate("MainWindow", "B"))
        self.label_11.setText(_translate("MainWindow", "Note 5"))
        self.label_8.setText(_translate("MainWindow", "Note 2"))
        self.label_16.setText(_translate("MainWindow", "Note 10"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "C"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "C#/Db"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "D"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "D#/Eb"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "E"))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "F"))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "F#/Gb"))
        self.comboBox_4.setItemText(8, _translate("MainWindow", "G"))
        self.comboBox_4.setItemText(9, _translate("MainWindow", "G#/Ab"))
        self.comboBox_4.setItemText(10, _translate("MainWindow", "A"))
        self.comboBox_4.setItemText(11, _translate("MainWindow", "A#/Bb"))
        self.comboBox_4.setItemText(12, _translate("MainWindow", "B"))
        self.comboBox.setItemText(1, _translate("MainWindow", "C"))
        self.comboBox.setItemText(2, _translate("MainWindow", "C#/Db"))
        self.comboBox.setItemText(3, _translate("MainWindow", "D"))
        self.comboBox.setItemText(4, _translate("MainWindow", "D#/Eb"))
        self.comboBox.setItemText(5, _translate("MainWindow", "E"))
        self.comboBox.setItemText(6, _translate("MainWindow", "F"))
        self.comboBox.setItemText(7, _translate("MainWindow", "F#/Gb"))
        self.comboBox.setItemText(8, _translate("MainWindow", "G"))
        self.comboBox.setItemText(9, _translate("MainWindow", "G#/Ab"))
        self.comboBox.setItemText(10, _translate("MainWindow", "A"))
        self.comboBox.setItemText(11, _translate("MainWindow", "A#/Bb"))
        self.comboBox.setItemText(12, _translate("MainWindow", "B"))
        self.label_17.setText(_translate("MainWindow", "Note 11"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "C"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "C#/Db"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "D"))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "D#/Eb"))
        self.comboBox_5.setItemText(5, _translate("MainWindow", "E"))
        self.comboBox_5.setItemText(6, _translate("MainWindow", "F"))
        self.comboBox_5.setItemText(7, _translate("MainWindow", "F#/Gb"))
        self.comboBox_5.setItemText(8, _translate("MainWindow", "G"))
        self.comboBox_5.setItemText(9, _translate("MainWindow", "G#/Ab"))
        self.comboBox_5.setItemText(10, _translate("MainWindow", "A"))
        self.comboBox_5.setItemText(11, _translate("MainWindow", "A#/Bb"))
        self.comboBox_5.setItemText(12, _translate("MainWindow", "B"))
        self.label_12.setText(_translate("MainWindow", "Note 6"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "C"))
        self.comboBox_9.setItemText(2, _translate("MainWindow", "C#/Db"))
        self.comboBox_9.setItemText(3, _translate("MainWindow", "D"))
        self.comboBox_9.setItemText(4, _translate("MainWindow", "D#/Eb"))
        self.comboBox_9.setItemText(5, _translate("MainWindow", "E"))
        self.comboBox_9.setItemText(6, _translate("MainWindow", "F"))
        self.comboBox_9.setItemText(7, _translate("MainWindow", "F#/Gb"))
        self.comboBox_9.setItemText(8, _translate("MainWindow", "G"))
        self.comboBox_9.setItemText(9, _translate("MainWindow", "G#/Ab"))
        self.comboBox_9.setItemText(10, _translate("MainWindow", "A"))
        self.comboBox_9.setItemText(11, _translate("MainWindow", "A#/Bb"))
        self.comboBox_9.setItemText(12, _translate("MainWindow", "B"))
        self.label_14.setText(_translate("MainWindow", "Note 8"))
        self.label_7.setText(_translate("MainWindow", "Note 1"))
        self.label_9.setText(_translate("MainWindow", "Note 3"))
        self.label_15.setText(_translate("MainWindow", "Note 9"))
        self.label_10.setText(_translate("MainWindow", "Note 4"))
        self.comboBox_11.setItemText(1, _translate("MainWindow", "C"))
        self.comboBox_11.setItemText(2, _translate("MainWindow", "C#/Db"))
        self.comboBox_11.setItemText(3, _translate("MainWindow", "D"))
        self.comboBox_11.setItemText(4, _translate("MainWindow", "D#/Eb"))
        self.comboBox_11.setItemText(5, _translate("MainWindow", "E"))
        self.comboBox_11.setItemText(6, _translate("MainWindow", "F"))
        self.comboBox_11.setItemText(7, _translate("MainWindow", "F#/Gb"))
        self.comboBox_11.setItemText(8, _translate("MainWindow", "G"))
        self.comboBox_11.setItemText(9, _translate("MainWindow", "G#/Ab"))
        self.comboBox_11.setItemText(10, _translate("MainWindow", "A"))
        self.comboBox_11.setItemText(11, _translate("MainWindow", "A#/Bb"))
        self.comboBox_11.setItemText(12, _translate("MainWindow", "B"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "C"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "C#/Db"))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "D"))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "D#/Eb"))
        self.comboBox_7.setItemText(5, _translate("MainWindow", "E"))
        self.comboBox_7.setItemText(6, _translate("MainWindow", "F"))
        self.comboBox_7.setItemText(7, _translate("MainWindow", "F#/Gb"))
        self.comboBox_7.setItemText(8, _translate("MainWindow", "G"))
        self.comboBox_7.setItemText(9, _translate("MainWindow", "G#/Ab"))
        self.comboBox_7.setItemText(10, _translate("MainWindow", "A"))
        self.comboBox_7.setItemText(11, _translate("MainWindow", "A#/Bb"))
        self.comboBox_7.setItemText(12, _translate("MainWindow", "B"))

